apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: php-app
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30036